name: Run Python Script Daily

on:
  schedule:
    - cron: '0 9 * * *'  # This runs the script daily at 9 AM UTC

jobs:
  run-script:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python C:\Users\kannanr\PycharmProjects\pythoninterviewTask\interviewTask\reverseString.py > output.txt

      - name: Send email with result
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          to: Kannan13111@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          subject: Daily Script Result
          body: |
            Please find the result attached.
          attachments: output.txt
